<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260121180954 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE variable (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, var_key VARCHAR(255) NOT NULL, var_value VARCHAR(255) NOT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CC4D878D166D1F9C ON variable (project_id)');
        $this->addSql('ALTER TABLE variable ADD CONSTRAINT FK_CC4D878D166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE variable DROP CONSTRAINT FK_CC4D878D166D1F9C');
        $this->addSql('DROP TABLE variable');
    }
}
